# Generated by Django 3.2 on 2024-01-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', help_text='Пользователь', max_length=100, verbose_name='Роль'),
        ),
    ]
