# Generated by Django 3.2 on 2024-01-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_password',
            field=models.CharField(default=1, help_text='Ваш токен', max_length=255, verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
