# Generated by Django 3.2 on 2024-01-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_token_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_password',
        ),
    ]
