# Generated by Django 3.2.16 on 2024-01-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('unit', models.CharField(choices=[('мл', 'миллилитр'), ('г', 'грамм'), ('л', 'литр'), ('чл', 'чайная ложка'), ('сл', 'столовая ложка'), ('шт', 'штука')], max_length=2, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='Тег')),
                ('color', models.CharField(max_length=16, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Resipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('cook_time', models.PositiveIntegerField()),
                ('author', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('tags', models.ManyToManyField(blank=True, help_text='Удерживайте Ctrl для выбора нескольких вариантов', to='menu.Tag', verbose_name='Теги')),
            ],
        ),
    ]
