# Generated by Django 3.2 on 2024-01-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resipt',
            new_name='Resipte',
        ),
    ]
