# Generated by Django 3.2 on 2024-01-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20240107_2311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resipte',
            new_name='Resipe',
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='unit',
            field=models.CharField(choices=[('мл', 'миллилитр'), ('г', 'грамм'), ('по вкусу', 'по вкусу'), ('стакан', 'стакан 300 мл'), ('л', 'литр'), ('горсть', 'горсть'), ('кг', 'килограммы'), ('пакет', 'пакет'), ('пучок', 'пучок'), ('кусок', 'кусок'), ('капля', 'капля'), ('щепотка', 'щепотка'), ('долька', 'долька'), ('банка', 'банка'), ('упаковка', 'упаковка'), ('ч. л.', 'чайная ложка'), ('ст. л.', 'столовая ложка'), ('веточка', 'веточка'), ('шт.', 'штука')], max_length=8, verbose_name='Единица измерения'),
        ),
    ]
