# Generated by Django 3.2 on 2024-01-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20240109_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingridient',
            old_name='unit',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingridient',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resipe',
            old_name='cook_time',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='resipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resipe',
            old_name='description',
            new_name='text',
        ),
        migrations.AddField(
            model_name='resipe',
            name='ingridients',
            field=models.ManyToManyField(blank=True, help_text='Удерживайте Ctrl для выбора нескольких ингридиентов', to='menu.Ingridient', verbose_name='Ингридиенты'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=30, verbose_name='Тег'),
        ),
    ]
