# Generated by Django 3.2 on 2024-01-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='user_shoppingcart_unique',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='menu.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user_shopping_cart_unique'),
        ),
    ]
