# Generated by Django 3.2 on 2024-01-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20240111_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='resipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/recipes/'),
        ),
        migrations.CreateModel(
            name='ResipeIngridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('ingridient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingridient')),
                ('resipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.resipe')),
            ],
        ),
        # migrations.AlterField(
        #    model_name='resipe',
        #   name='ingridients',
        #    field=models.ManyToManyField(blank=True, help_text='Удерживайте Ctrl для выбора нескольких ингридиентов', through='menu.ResipeIngridient', to='menu.Ingridient', verbose_name='Ингридиенты'),
        # ),
        migrations.RemoveField(
            model_name='resipe',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='resipe',
            name='ingridients',
            field=models.ManyToManyField(blank=True, help_text='Удерживайте Ctrl для выбора нескольких ингридиентов', through='menu.ResipeIngridient', to='menu.Ingridient', verbose_name='Ингридиенты'),
        ),
    ]
