# Generated by Django 3.2 on 2024-01-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20240122_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
