# Generated by Django 3.2 on 2024-01-30 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20240128_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Укажите время приготовления (в минутах)', validators=[django.core.validators.MinValueValidator(1, message='Время приготовления должно быть не менее 1 минуты!')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Укажите slug', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
